extraction:
 javascript:
  index:
   exclude:
    - dist
    - out
   filters:
    - exclude: ['node_modules', 'dist', 'out', 'build', '*.min.*', '*.bundle.*', '*.map', '*.dev.*']
   filetypes:
    # ".ejs": "html"
